- name: Fetch CVEs for given host
  hosts: localhost
  gather_facts: no
  vars:
    access_token: "<your_token_here>"  # Or pass via set_fact from previous playbook
    host_id: "94c98263-6f88-4949-b9b1-d7ed86599cd9"
    cve_url: "https://console.redhat.com/api/vulnerability/v1/cves?affected_host={{ host_id }}"
  tasks:
    - name: Query CVEs for the given host
      uri:
        url: "{{ cve_url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        return_content: yes
      register: cve_response

    - name: Show CVEs
      debug:
        var: cve_response.json.data